baseURL = "https://blogpagenotices.github.io/"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
theme = "PaperMod"
googleAnalytics = "G-PBE4RX49LR"
enableRobotsTXT = true

[languages]
  [languages.es]
    languageCode = "es-es"
    languageName = "Español"
    weight = 1
    title = "GTA 6 Noticias"
    [languages.es.params]
      description = "Noticias, guias y teorias sobre GTA 6"
    [[languages.es.menu.main]]
      name = "Inicio"
      url = "/"
      weight = 1
    [[languages.es.menu.main]]
      name = "Articulos"
      url = "/posts/"
      weight = 2
    [[languages.es.menu.main]]
      name = "Sobre nosotros"
      url = "/about/"
      weight = 3
    [[languages.es.menu.main]]
      name = "Contacto"
      url = "/contact/"
      weight = 4
    [[languages.es.menu.main]]
      name = "Privacidad"
      url = "/privacy/"
      weight = 5

  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 2
    title = "GTA 6 News"
    [languages.en.params]
      description = "News, guides and theories about GTA 6"
    [[languages.en.menu.main]]
      name = "Home"
      url = "/en/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Articles"
      url = "/en/posts/"
      weight = 2
    [[languages.en.menu.main]]
      name = "About"
      url = "/en/about/"
      weight = 3
    [[languages.en.menu.main]]
      name = "Contact"
      url = "/en/contact/"
      weight = 4
    [[languages.en.menu.main]]
      name = "Privacy Policy"
      url = "/en/privacy/"
      weight = 5

[params]
  env = "production"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowToc = true
